# Generated by Django 5.1 on 2024-10-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(max_length=255)),
                ("collection_number", models.CharField(max_length=50)),
                ("cup_size", models.CharField(max_length=50)),
                ("discount", models.CharField(max_length=50)),
                ("coupon_name", models.CharField(max_length=255)),
                ("expiration_date", models.DateField()),
            ],
        ),
    ]
