# Generated by Django 5.1 on 2025-01-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Kouponapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotion",
            name="count",
            field=models.PositiveIntegerField(default=1, verbose_name="จำนวนคูปอง"),
        ),
    ]
