# Generated by Django 5.1 on 2024-12-25 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Kouponapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotion",
            name="cups",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="จำนวนแก้วที่สะสม"
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="ส่วนลด",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="free",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="จำนวนแก้วที่ฟรี"
            ),
        ),
    ]
