# Generated by Django 5.1 on 2025-01-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Kouponapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeownerrequest",
            name="shop_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ชื่อร้าน"
            ),
        ),
    ]
