# Generated by Django 5.1 on 2025-01-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Kouponapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="used",
            field=models.BooleanField(default=False, verbose_name="ตรวจสอบการใช้งาน"),
        ),
        migrations.AddField(
            model_name="coupon",
            name="used_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="เวลาที่ใช้งาน"
            ),
        ),
    ]
