# Generated by Django 5.1 on 2025-01-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Kouponapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="qr_code_image",
        ),
        migrations.AddField(
            model_name="coupon",
            name="collect_qr_code_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="qr_codes/",
                verbose_name="ภาพ QR Code สำหรัลสะสมคูปอง",
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="use_qr_code_url_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="qr_codes/",
                verbose_name="ภาพ QR Code สำหรับใช้คูปอง",
            ),
        ),
    ]
