# Generated by Django 5.1 on 2024-12-13 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Kouponapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coupon",
            options={"verbose_name": "คูปอง", "verbose_name_plural": "คูปอง"},
        ),
        migrations.AlterModelOptions(
            name="member",
            options={"verbose_name": "สมาชิก", "verbose_name_plural": "สมาชิก"},
        ),
        migrations.AlterModelOptions(
            name="owner",
            options={"verbose_name": "เจ้าของร้าน", "verbose_name_plural": "เจ้าของร้าน"},
        ),
        migrations.AlterModelOptions(
            name="promotion",
            options={"verbose_name": "โปรโมชั่น", "verbose_name_plural": "โปรโมชั่น"},
        ),
        migrations.AlterModelOptions(
            name="store",
            options={"verbose_name": "ร้าน", "verbose_name_plural": "ร้าน"},
        ),
        migrations.AlterField(
            model_name="coupon",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ไอดีคูปอง"
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Kouponapp.member",
                verbose_name="สมาชิกที่ใช้งานคูปอง",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="promotion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Kouponapp.promotion",
                verbose_name="ไอดีโปรโมชั่น",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="used",
            field=models.BooleanField(default=False, verbose_name="ตรวจสอบการใช้งาน"),
        ),
        migrations.AlterField(
            model_name="member",
            name="phone",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="เบอร์โทรศัพท์"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="profile_img",
            field=models.ImageField(
                blank=True, null=True, upload_to="profiles/", verbose_name="รูปโปรไฟล์"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ชื่อผู้ใช้",
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="เบอร์โทรศัพท์"
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="shop_logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="shop_logos/", verbose_name="โลโก้ร้าน"
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ชื่อผู้ใช้",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="cups",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="จำนวนแก้วที่สะสม"
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="cupsize",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="ขนาดแก้ว"
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="ส่วนลด",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="end",
            field=models.DateField(verbose_name="วันหมดอายุคูปอง"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="free",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="จำนวนแก้วที่ฟรี"
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="name",
            field=models.CharField(max_length=255, verbose_name="ชื่อโปรโมชั่น"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="promotions/", verbose_name="รูปโปรโมชั่น"
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="start",
            field=models.DateField(verbose_name="วันที่เริ่มใช้งานคูปอง"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotions",
                to="Kouponapp.store",
                verbose_name="ชื่อร้าน",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stores",
                to="Kouponapp.owner",
                verbose_name="เจ้าของร้าน",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="store_name",
            field=models.CharField(max_length=255, unique=True, verbose_name="ชื่อร้าน"),
        ),
    ]
