# Generated by Django 5.1 on 2025-01-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Kouponapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="promotion_count",
            field=models.PositiveIntegerField(verbose_name="ลำดับคูปอง"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="details",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="รายละเอียดโปรโมชั่น"
            ),
        ),
    ]
