# Generated by Django 5.1 on 2025-01-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Kouponapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="collect",
        ),
    ]
