# Generated by Django 5.1 on 2025-01-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Kouponapp", "0002_alter_coupon_promotion_count_alter_promotion_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="qr_code_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="qr_codes/", verbose_name="ภาพ QR Code"
            ),
        ),
    ]
