# Generated by Django 5.1 on 2025-01-31 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Kouponapp", "0002_storeownerrequest_shop_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="promotion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupons",
                to="Kouponapp.promotion",
                verbose_name="ไอดีโปรโมชั่น",
            ),
        ),
    ]
