# Generated by Django 5.1 on 2025-02-11 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Kouponapp", "0002_member_wallet_balance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="wallet_balance",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
