# Generated by Django 5.1 on 2025-02-11 08:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Kouponapp", "0003_remove_member_wallet_balance_delete_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=300.0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="ยอดเงินคงเหลือ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่สร้าง"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="อัพเดทล่าสุด"),
                ),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to="Kouponapp.member",
                        verbose_name="เจ้าของกระเป๋าเงิน",
                    ),
                ),
            ],
            options={
                "verbose_name": "กระเป๋าเงิน",
                "verbose_name_plural": "กระเป๋าเงินทั้งหมด",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="จำนวนเงิน",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("DEBIT", "หักเงิน"), ("CREDIT", "เพิ่มเงิน")],
                        max_length=6,
                        verbose_name="ประเภทธุรกรรม",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="รายละเอียด"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่ทำรายการ"),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="Kouponapp.wallet",
                        verbose_name="กระเป๋าเงิน",
                    ),
                ),
            ],
            options={
                "verbose_name": "ประวัติธุรกรรม",
                "verbose_name_plural": "ประวัติธุรกรรมทั้งหมด",
                "ordering": ["-created_at"],
            },
        ),
    ]
