# Generated by Django 5.1 on 2025-01-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Kouponapp", "0003_coupon_qr_code_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="promotion_count",
            field=models.PositiveIntegerField(default=0, verbose_name="ลำดับคูปอง"),
        ),
    ]
