# Generated by Django 5.1 on 2025-01-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Kouponapp", "0004_alter_coupon_promotion_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScannedCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.CharField(max_length=500)),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
