# Generated by Django 5.1 on 2025-01-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Kouponapp", "0004_alter_coupon_promotion_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScannedQRCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scanned_text", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_url", models.BooleanField(default=False)),
            ],
        ),
    ]
