# Generated by Django 5.1 on 2025-02-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Kouponapp", "0005_alter_wallet_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="card_number",
            field=models.CharField(
                blank=True, max_length=16, null=True, unique=True, verbose_name="เลขบัตร"
            ),
        ),
    ]
