# Generated by Django 5.1 on 2025-02-13 05:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Kouponapp", "0006_member_card_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="ราคาสินค้า",
            ),
        ),
    ]
