# Generated by Django 5.1 on 2025-03-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Kouponapp", "0007_promotion_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="profile_img",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="profiles/",
                verbose_name="รูปโปรไฟล์",
            ),
        ),
    ]
