# Generated by Django 5.1 on 2025-03-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Kouponapp", "0008_alter_member_profile_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("DEBIT", "จ่ายเงิน"), ("CREDIT", "รับเงิน")],
                max_length=6,
                verbose_name="ประเภทธุรกรรม",
            ),
        ),
    ]
