# Generated by Django 5.1 on 2025-05-13 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Kouponapp", "0009_alter_transaction_transaction_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="storeownerrequest",
            constraint=models.UniqueConstraint(
                fields=("user",), name="unique_store_owner_request"
            ),
        ),
    ]
