# Generated by Django 5.1 on 2025-05-13 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Kouponapp", "0010_storeownerrequest_unique_store_owner_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stores",
                to="Kouponapp.member",
                verbose_name="เจ้าของร้าน",
            ),
        ),
    ]
